### ISSUE TITLE
Simplify authorization render handling

### ISSUE THREAD

**Issue by dresha-dev** [podgorniy/media-manager#3]
Instead of composing components which should be rendered for authenticated user we can make this design once at the top of the render method
https://github.com/podgorniy/media-manager/blob/0c3173c777891ef8a78b833b892678453baa995a/src/client/components/MainView.tsx#L18-L25

**Comment by podgorniy** [comment]
Еще рано оптимизировать рендер компонент. Задача компонента - просто отрендерить те кусочки что у нас есть. Он не останется в том виде в котором есть.

**Comment by dresha-dev** [comment]
Я бы не сказал что это оптимизация, просто небольшой импрувмент по
читабельность кода :)
