### ISSUE TITLE
Автоматически создавать dummy аккаунт при разработке

### ISSUE THREAD

**Issue by podgorniy** [podgorniy/media-manager#5]
DOD:
- в дев режиме создается dummy аккаунт (name: usrer, password: 123). Если аккаунт есть, создавать его не надо
- в прод режиме не делать ничего
- добавить описание про аккаунт и его поведение в секцию "Как запустить проект для разработки"

**Comment by dresha-dev** [comment]
По коду видно, что в DOD, валидным остался только пункт:

> * добавить описание про аккаунт и его поведение в секцию "Как запустить проект для разработки"

Или я что-то не так понял 🤔 ?

**Comment by podgorniy** [comment]
Все верно
