### ISSUE TITLE
Включить некоторые настройки редакторов (webstorm, vscode) в код репозитория

### ISSUE THREAD

**Issue by podgorniy** [podgorniy/media-manager#6]
Rationale

В процессе разработки и в результате билдов содаются файлы, которые не хотелось бы включать в поиск в редакторе. Имеет смысл добавить настройки исключения файлов и папок в репозиторий чтобы упростить старт работы с проектом. Сейчас любые настройки проекта не вложены в репозиторий.

DOD
- исключенные папки из поиска: `build`, `.dev`. Исключены файлы `package-lock.json` (если возможно)
- только настройки исключения папкок/файлов для редакторов WebStorm и VS code вложены в репозиторий

**Comment by dresha-dev** [comment]
He очень понятно DOD 
Поиск - это _.gitignore_ file или специфические настройки редактора 🤔 
Как я понял DOD это пофиксить gitignore file
1. Исключить (добавить в git ignore) `build/`, .`dev/`, `package-lock.json`
2. Исключить папки и файлы которые автоматически добавляются редакторами

Если пункты выше соответствуют поставленым задачам, то я готов взяться.
Для пункта 2. буду использовать сервис https://www.gitignore.io/ со следующими настройками  https://www.gitignore.io/api/node,webstorm,visualstudio если есть пожелания добавить что-то ещё, дай знать

**Comment by podgorniy** [comment]
Суть в том чтобы настройки редактора касательно исключенных папок лежала в репозитории.

Т.е. шаги

1. Создать настройки согласно описанию
2. Поправить .gitignore чтобы эти настройки трекались гитом
